# Author: Bekhruz Malikov
import rp2
import machine
from machine import Pin
import time

# machine.freq(125_000_000) # downclock MCU by 5 MHz (125 MHz)
MOTOR_PINS = [6, 5, 4, 3] # GPIO on PicoW

################################################################
### @rp2.asm_pio(...) takes the Python function defined,
### wraps it with a decorator, and converts it into a low-level
### PIO program that the RP2040 can run directly on its hardware
### state machine, helpful for sending packets to the ESC ###
################################################################

@rp2.asm_pio(
    out_shiftdir=rp2.PIO.SHIFT_LEFT, #Read bits left to right (MSB first) — DShot requires this
    autopull=False, # don't grab data yet 
    set_init=rp2.PIO.OUT_LOW, # SET pin starts LOW
    out_init=rp2.PIO.OUT_LOW, # The OUTPUT pin starts LOW
    sideset_init=rp2.PIO.OUT_LOW # Signal wire to ESC starts LOW
    )

############################
### Dshot() ###
# sequence of moving bits from Pico to ESC - generated by Pico W CPU
# the sequence of bits contains information about the throttle, telemetry, and CRC
############################
def dshot():
    # ESC signal must stay low during fetching/pull of bits from CPU
    pull(block).side(0)
    
    set(x, 15).side(0) # set length of packet to 16
    
    # BIT LOOP STATE
    label("bitloop") # just a label
    out(y, 1).side(1) # pass into Y register to shift the packet by 1 bit, then check if bit is 0 or 1
    jmp(not_y, "zero").side(1)
    
    # BIT 1 STATE - hold HIGH for two clock cycles longer 
    label("one")
    nop().side(1) 
    nop().side(1)
    
    jmp(x_dec, "bitloop").side(0) # count down to 0th bit
    jmp("done").side(0)
    
    # BIT 0 STATE - hold LOW for two clock cycles longer
    label("zero")
    nop().side(0)
    nop().side(0)
    
    jmp(x_dec, "bitloop").side(0)
    
    # DONE STATE - hold LOW for one clock cycle 
    label("done")
    nop().side(0)
 
############################
### makeshot() ### 
# helpers for making the packets of bits for throttle
############################
def make_packet(throttle, telemetry=False):
    packet = (throttle << 1) | (1 if telemetry else 0) # shift left by 1 to make space for telemetry flag bit
    crc = ((packet ^ (packet >> 4) ^ (packet >> 8))) & 0x0F # unique fingerprint; 0x0F = 15 
    return (packet << 4) | crc # make room for crc bits 


####################################
### send_dshot() ###
# sends the dshot packet to the ESC
###################################

def send_dshot(state_machine, throttle):
    packet = make_packet(throttle)
    state_machine.put(packet << 16) # shift 16 bits left from 32 to be read by sm

#####################################
### Initialize the state machine  ###
#####################################
DSHOT_FREQUENCY = 2_400_000 # cycles per second -> DSHOT 150
state_machines = [
    rp2.StateMachine(
        0, # 0th state machine 
        dshot, # the sequence of actions to run
        freq=DSHOT_FREQUENCY, # run state machine at 2.4 MHz, system at 250 MHz
        sideset_base=Pin(MOTOR_PINS[0])), 
    rp2.StateMachine(
        1, # 1st state machine
        dshot,
        freq=DSHOT_FREQUENCY,
        sideset_base=Pin(MOTOR_PINS[1])), 
    rp2.StateMachine(
        2, # 1st state machine
        dshot,
        freq=DSHOT_FREQUENCY,
        sideset_base=Pin(MOTOR_PINS[2])), 
    rp2.StateMachine(
        3, # 4th state machine
        dshot,
        freq=DSHOT_FREQUENCY,
        sideset_base=Pin(MOTOR_PINS[3]))
    ]

for sm in state_machines:
    sm.active(1) # set state machine to running mode 

#####################################
### Arm the ESCs  ###
# Uses state machine, then dshot()  #
# for sending pulses to ESC         #
#####################################
# status_led = Pin(2, Pin.OUT)
target_sm=state_machines[0]

print("Arming ESC for 2 seconds")
# for _ in range(5000):
#     send_dshot(target_sm, 0) # test for 200 milliseconds = 2 seconds 
#     time.sleep_ms(1) # 1s delay

while True: 
    send_dshot(target_sm, 20) # test for 200 milliseconds = 2 seconds 
    time.sleep_ms(1) # 1s delay
    

# for _ in range(10000):  
#     send_dshot(state_machine_0, 48) # test for 200 milliseconds = 2 seconds 
#     time.sleep_ms(1)








# p = [Pin(MOTOR_PINS[0], Pin.OUT), Pin(MOTOR_PINS[1], Pin.OUT), Pin(MOTOR_PINS[2], Pin.OUT), Pin(MOTOR_PINS[3], Pin.OUT)]
# while True: 
#     p[3].high()
#     time.sleep_ms(500)
#     p[3].low()
#     time.sleep_ms(500)
#     p[0].high()
#     time.sleep_ms(500)
#     p[0].low()
#     time.sleep_ms(500)
#     p[1].high()
#     time.sleep_ms(500)
#     p[1].low()
#     time.sleep_ms(500)
#     p[2].high()
#     time.sleep_ms(500)
#     p[2].low()
#     time.sleep_ms(500)



#####################################
####    REFERENCES (PIO)          ###
####   Assembly instructions      ###
#####################################

# Instruction  | What it does
# -------------|--------------------------------------------------------------
# pull         | Fetches the next packet from Python into the PIO holding buffer (FIFO)
# block        | Modifier for pull - Nothing transmitted until a real packet arrives
# noblock      | Modifier for pull - Reuse last packet if no new one is ready
# .side(0)     | Simultaneously sets ESC/GPIO signal wire LOW during the instruction (important!)
# .side(1)     | Simultaneously sets ESC/GPIO signal wire HIGH during the instruction (important!)
# jmp          | Jump to a label, can be conditional e.g. jmp(not_y, "zero")
# nop          | No Operation - waste exactly one clock cycle to control timing
# label        | Marks a named spot in code that jmp can jump back to
# set          | Load a number into a register e.g. set(x, 15) sets counter to 15
# out          | Shift bits from holding buffer into a register e.g. out(y, 1)
# active       | Sets or indicates whether state machine is on or not 

# Functions: 
    # dshot()
        # is the middleman toolchain that:
        # Pulls the packet out of the CPU queue
        # Breaks it apart bit by bit
        # Translates each bit into precise electrical HIGH/LOW timing on the wire
        # Repeats until all 16 bits are delivered


# Visuals:
    # Visual 1.1: Dshot() 
        # 1. Pull 16-bit packet from CPU queue
           # ↓
        # 2. If no new packet, reuse last one
            # ↓
        # 3. Set counter to 15 (will count down to 0 = 16 bits total)
           #  ↓
        # 4. Pull ESC wire HIGH (start of bit)
           #  ↓
        # 5. Shift 1 bit into Y register
           #  ↓
        # 6. Was that bit a 1 or 0?
           #   /        \
        #   bit=1       bit=0
       #   stay HIGH   go LOW
       #   longer      sooner
       #      \        /
       # 7. Counter - 1, loop back to step 4
           #     ↓
        # 8. Counter hit 0? All 16 bits sent → done
        
    # Visual 1.2: Dshot()
    ####### 
        # Pico RP2040 CPU
        #         ↓
        # runs make_packet()      ← Pico CPU does this math
        #         ↓
        # sm.put(packet << 16)    ← Pico CPU pushes to FIFO
        #         ↓
        # PIO state machine       ← Pico PIO takes over
        #         ↓
        # .side() toggles wire    ← physical signal to ESC
        #         ↓
        # ESC receives DShot
        #         ↓
        # Motor spins 
    ####### 

    # Visual 1.3: Dshot()
    #######
    # 1 DShot packet
        #├── 16 bits
        #│   ├── 11 bits = throttle value (0–2047)
        #│   ├── 1 bit  = telemetry flag
        #│   └── 4 bits = CRC checksum
        #│
        #└── each bit = 8 PIO cycles (.side() commands)
                    #├── 2 cycles HIGH + 6 cycles LOW = bit "0" (for 8 cycles, different for 5 cycles)
                    #└── 6 cycles HIGH + 2 cycles LOW = bit "1"


# Terminology
    # CRC
        # stands for Cyclic Redundancy Check— it's a checksum, basically a fingerprint of your packet.
        # prevents making corrupted packets of data, so a unique fingerprint is assigned
    # Telemetry
        # a request flag to send back all data about motors
    # ^
        # XOR operation: Exclusive OR
        # Output is 1 if the bits are DIFFERENT, 0 if they are the SAME

# Important Explanations
    # 1. This means if the ESC receives the packet and XORs the same chunks together,
    # it should get the same CRC fingerprint back. If even one bit changed during
    # transmission, the fingerprint won't match and the ESC knows something went wrong.

