# Author: Bekhruz Malikov
import rp2
import machine
from machine import Pin
import time

machine.freq(120_000_000) # 20 MHz --> 20 cycles per second 
MOTOR_PINS = [6, 5, 4, 3] # GPIO on PicoW

################################################################
### @rp2.asm_pio(...) takes the Python function defined,
### wraps it with a decorator, and converts it into a low-level
### PIO program that the RP2040 can run directly on its hardware
### state machine, helpful for sending packets to the ESC ###
################################################################

@rp2.asm_pio(
    out_shiftdir=rp2.PIO.SHIFT_LEFT, #Read bits left to right (MSB first) — DShot requires this
    autopull=False, # don't grab data yet 
    set_init=rp2.PIO.OUT_LOW, # SET pin starts LOW
    out_init=rp2.PIO.OUT_LOW, # The OUTPUT pin starts LOW
    sideset_init=rp2.PIO.OUT_LOW # Signal wire to ESC starts LOW
    )

############################
### Dshot() ###
# sequence of moving bits from Pico to ESC - generated by Pico W CPU
# the sequence of bits contains information about the throttle, telemetry, and CRC
############################
def dshot():
    # ESC signal must stay low during fetching/pull of bits from CPU
    pull(block).side(0) 
    
    set(x, 15).side(0) # set length of packet to 16
    
    # BIT LOOP STATE
    label("bitloop") # just a label
    out(y, 1).side(1)  # pass into Y register to shift the packet by 1 bit, then check if bit is 0 or 1
    jmp(not_y, "zero").side(1) 
    
    # BIT 1 STATE - hold HIGH for two clock cycles longer 
    label("one") 
    nop().side(1) 
    nop().side(1) 
    
    jmp(x_dec, "bitloop").side(0) # count down to 0th bit
    jmp("done").side(0)

    # BIT 0 STATE - hold LOW for two clock cycles longer
    label("zero")
    nop().side(0) 
    nop().side(0) 

    jmp(x_dec, "bitloop").side(0) 

    label("done")
    nop().side(0)

 
############################
### makeshot() ### 
# helpers for making the packets of bits for throttle
############################
def make_packet(throttle, telemetry=False):
    packet = (throttle << 1) | (1 if telemetry else 0) # shift left by 1 to make space for telemetry flag bit
    crc = ((packet ^ (packet >> 4) ^ (packet >> 8))) & 0x0F # unique fingerprint; 0x0F = 15 
    return (packet << 4) | crc # make room for crc bits 


####################################
### send_dshot() ###
# sends the dshot packet to the ESC
###################################

def send_dshot(state_machine, throttle):
    packet = make_packet(throttle)
    state_machine.put(packet << 16) # shift 16 bits left from 32 to be read by sm


#####################################
### Initialize the state machine  ###
#####################################
DEBUG_FREQUENCY = 2_400_000 # cycles per second --> 24 cyc/s / 5 cyc / bit = 4.8 
state_machines = [
    rp2.StateMachine(
        0, # 0th state machine 
        dshot, # the sequence of actions to run
        freq=DEBUG_FREQUENCY, # run state machine at 2.4 MHz, system at 250 MHz
        sideset_base=Pin(MOTOR_PINS[0])), 
    ]


state_machines[0].active(1)

test_packet = 0b0000_0000_1111_1111  # --> the ESC packet, generated after make_packet + send_dshot

expected = make_packet(throttle=15)
hand_calculated = 0b0000_0001_1110_1111
if (expected == hand_calculated):
    print(f"{expected} == {hand_calculated}")

print("Led should blink now: ")
while True:
    send_dshot(state_machines[0], throttle=0)
    # state_machines[0].put(test_packet << 16)
    time.sleep_ms(10000) # Give plenty of time for the 16-bit visual sequence to end

print(len(bin(test_packet)) - 2) # len of bitstream 




